### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by yash244466666** [yash244466666/Catalog-of-My-things#25]
project link: `https://github.com/yash244466666/Catalog-of-My-things/projects/1`
Note

There are three members in our team
Team member 1: @SabiMantock
Team member 2: @MNisarAli
Team member 3: @yash244466666

**Comment by 1GORDON** [comment]
##
## Hi @yash244466666, @SabiMantock, & @MNisarAli ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly ensure [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task)  have a corresponding card in the Kanban board. At the moment your Kanban board only consists of individual tasks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
